name = "AbstractOperators"
uuid = "d9c5613a-d543-52d8-9afd-8f241a8c3f1c"
version = "0.4.0"

[deps]
FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OperatorCore = "3945cd23-d97e-4db0-9df2-35342dbd287d"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

[weakdeps]
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"

[extensions]
GpuExt = "GPUArrays"
LinearMapsExt = "LinearMaps"

[compat]
FastBroadcast = "0.3.5"
GPUArrays = "11.2.3"
LinearAlgebra = "1"
LinearMaps = "3.11.4"
OperatorCore = "0.1"
Polyester = "0.7.18"
Random = "1.11.0"
RecursiveArrayTools = "2, 3"
julia = "1.10"

[workspace]
projects = ["test", "docs", "DSPOperators", "FFTWOperators", "NFFTOperators", "WaveletOperators"]