name = "NFFTOperators"
uuid = "35a93202-2abf-4a13-bc94-0aee2f861ee0"
version = "0.1.0"

[deps]
AbstractOperators = "d9c5613a-d543-52d8-9afd-8f241a8c3f1c"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
NFFTTools = "7424e34d-94f7-41d6-98a0-85abaf1b6c91"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

[compat]
AbstractOperators = "0.4"
Aqua = "0.8"
FFTW = "1.8.1"
FastBroadcast = "0.3.5"
LinearAlgebra = "1.11.0"
NFFT = "0.13.7"
NFFTTools = "0.2.6"
Polyester = "0.7.18"
Random = "1.11.0"
RecursiveArrayTools = "2, 3"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Random", "RecursiveArrayTools", "Test"]
