name = "DSPOperators"
uuid = "d5a72628-6e2f-430e-82f5-561df0bb8116"
version = "0.1.0"

[deps]
AbstractOperators = "d9c5613a-d543-52d8-9afd-8f241a8c3f1c"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "DSP", "Random", "RecursiveArrayTools", "Test"]

[compat]
AbstractOperators = "0.4"
Aqua = "0.8"
DSP = "0.7, 0.8"
FFTW = "1.9.0"
LinearAlgebra = "1.10.0"
Random = "1.10.0"
RecursiveArrayTools = "2, 3"
Test = "1"
julia = "1.10"
